### ISSUE TITLE
Unit tests for OpenCog MST-Parser

### ISSUE THREAD

**Issue by akolonin** [singnet/language-learning#169] opened 2019-02-12 10:02 UTC
We need existing functionality of the OpenCog MST-Parser covered with unit tests. Tentatively, here is the list of unit tests that should be create, passing, and included into CircleCI framework being used for OpenCog project:
1) MI-Observer
1-a) Take simple corpus like http://langlearn.singularitynet.io/data/poc-turtle/poc-turtle.txt and provide expected MI-counts such as http://langlearn.singularitynet.io/data/poc-turtle/poc-turtle-fmi.txt based on LG-ANY link creation mode
1-b) Same as above for window-based link creation mode with account for distance
1-c) Same as above for window-based link creation mode w/o account for distance
2) MST-Parser
2-a) Take simple corpus like http://langlearn.singularitynet.io/data/poc-turtle/poc-turtle.txt and provide expected parses such as http://langlearn.singularitynet.io/data/poc-turtle/poc-turtle-parses.txt with account for distance
2-b) Same as above w/o account for distance
3) Test case of "ull" file with input sentence-bound mutual information passed as input for MST-Parser and provide expected parses, accordingly to the #167

**Comment by akolonin** [comment] 2019-02-28 08:32
Related issue and PR suggested by @AmeBel :
... on link-grammar the unit-tests exist but setting-up ci wasn't accepted last time https://github.com/opencog/link-grammar/pull/162#issuecomment-226165469, ... Another option is to have unit-tests for the docker-images, that is dependency management. When a new version of link-grammar is published then  the docker-images will install it only if all the tests in the pipeline pass. If this option is chosen I will deal with the setup. Have done something similar, but not automated, in the past see https://github.com/opencog/ocpkg/pull/102

**Comment by glicerico** [comment] 2019-04-17 14:41
Implemented unit tests and circleci integration in PR https://github.com/singnet/learn/pull/16/files
The tests are not as described above, but as we discussed in respective videocall. Check test files to see details.
I believe someone with access to circleci singnet credentials needs to add the project for it to be automatically built. I'm trying  to tag @amen but cant do it

**Comment by AmeBel** [comment] 2019-04-18 04:50
The tests have been running for couple of months

**Comment by glicerico** [comment] 2019-04-18 05:06
@AmeBel , even if the issue is in the language-learning repo, it refers to the ULL functionality in the "learn" repo, which I don't think was setup

**Comment by AmeBel** [comment] 2019-04-18 05:22
I missed that. I have enabled the test, it should run once the pr is merged.

**Comment by akolonin** [comment] 2019-05-05 17:01
@glicerico, @AmeBel - can we close this now, assuming that we have the unit tests enabled and running?

**Comment by glicerico** [comment] 2019-05-05 20:28
> can we close this now, assuming that we have the unit tests enabled and running?
Yes

**Closed** 2019-05-06 01:58 UTC
Labels: doing
